import json
import boto3
import os
import datatier

from configparser import ConfigParser

def lambda_handler(event, context):
  try:
    print("**STARTING**")
    print("**lambda: final_new_game**")
    
    #
    # setup AWS based on config file:
    #
    config_file = 'config.ini'
    os.environ['AWS_SHARED_CREDENTIALS_FILE'] = config_file
    
    configur = ConfigParser()
    configur.read(config_file)

    #
    # configure for RDS access
    #
    rds_endpoint = configur.get('rds', 'endpoint')
    rds_portnum = int(configur.get('rds', 'port_number'))
    rds_username = configur.get('rds', 'user_name')
    rds_pwd = configur.get('rds', 'user_pwd')
    rds_dbname = configur.get('rds', 'db_name')


    #
    # Grab the saveid of the player
    #

    if "trainername" in event:
      trainername = event["trainername"]
    elif "pathParameters" in event:
      if "trainername" in event["pathParameters"]:
        trainername = event["pathParameters"]["trainername"]
      else:
        raise Exception("requires trainername parameter in pathParameters")
    else:
        raise Exception("requires trainername parameter in event")
        
    print("trainername:", trainername)

    #
    # open connection to the database:
    #
    print("**Opening connection**")
    
    dbConn = datatier.get_dbConn(rds_endpoint, rds_portnum, rds_username, rds_pwd, rds_dbname)
    
    #
    # insert into gamesave DB:
    #
    print("**Inserting...**")

    sql = "INSERT INTO gamesave (trainername) VALUES (%s)";

    rows_modified = datatier.perform_action(dbConn, sql, [trainername])

    if rows_modified > 0:
       # Fetch the last autogenerated ID after the INSERT
        sql_get_last_id = "SELECT LAST_INSERT_ID() AS last_id"
        last_inserted_row = datatier.retrieve_one_row(dbConn, sql_get_last_id)
        
        # Extract the last autogenerated ID from the retrieved row
        generated_saveid = last_inserted_row[0] 

    else: 
      print("**Couldn't create a new game, returning...**")
      return {
        'statusCode': 400,
        'body': json.dumps("insert failed")
      }
    
    #
    # insert into inventory table
    #
    print("**creating inventory...**")

    sql = "INSERT INTO inventory (saveid, pokeballs, coins) VALUES (%s, 10, 0)";

    rows_modified = datatier.perform_action(dbConn, sql, [generated_saveid])

    if rows_modified < 0:
      print("**Couldn't create a new inventory, returning...**")
      return {
        'statusCode': 400,
        'body': json.dumps("insert failed")
      }

    #
    # respond in an HTTP-like way, i.e. with a status
    # code and body in JSON format:
    #
    print("**DONE, returning the generated saveid**")
    
    return {
      'statusCode': 200,
      'body': json.dumps(generated_saveid)
    }
    
  except Exception as err:
    print("**ERROR**")
    print(str(err))
    
    return {
      'statusCode': 400,
      'body': json.dumps(str(err))
    }
